name: Update PDF and README from LaTeX

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  latex-to-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install LaTeX & Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full pandoc

      - name: Compile LaTeX to PDF
        run: pdflatex -interaction=nonstopmode -jobname=CV_RiccardoPeriotto main.tex

      - name: Convert PDF to Markdown
        run: pandoc CV_RiccardoPeriotto.pdf -o README.md

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "Automatic compilation and update."
            git push
          fi